version: '3'

services:
  mongodb:
    image: mongo:4.0.0-rc6
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"

  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
    command: npm start
    depends_on:
      - mongodb

